# Generated by Django 3.2.25 on 2025-03-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('__data_processor__', '0021_remove_schooldata_address_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolRemovalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=7)),
                ('agency_type', models.CharField(max_length=50)),
                ('cesa', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=50)),
                ('district_code', models.CharField(max_length=10)),
                ('school_code', models.CharField(max_length=10)),
                ('grade_group', models.CharField(max_length=50)),
                ('charter_ind', models.CharField(max_length=4)),
                ('district_name', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('group_by', models.CharField(max_length=50)),
                ('group_by_value', models.CharField(max_length=200)),
                ('removal_type_description', models.CharField(max_length=200)),
                ('tfs_enrollment_count', models.CharField(max_length=20)),
                ('removal_count', models.CharField(max_length=20)),
                ('percent_of_group', models.CharField(max_length=20)),
            ],
        ),
    ]
