# Generated by Django 3.2.25 on 2025-03-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('__data_processor__', '0022_schoolremovaldata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolremovaldata',
            name='percent_of_group',
        ),
    ]
