# Generated by Django 3.2.25 on 2025-03-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('__data_processor__', '0023_remove_schoolremovaldata_percent_of_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetopioStateWideRemovalDataTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(default='State', max_length=50)),
                ('geoid', models.CharField(default='WI', max_length=50)),
                ('topic', models.CharField(default='FVDEWVAR', max_length=50)),
                ('stratification', models.TextField(blank=True)),
                ('period', models.CharField(max_length=20)),
                ('value', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Metopio Statewide Removal Data Transformation',
                'verbose_name_plural': 'Metopio Statewide Removal Data Transformations',
                'ordering': ['period', 'stratification'],
            },
        ),
    ]
