# Generated by Django 3.2.25 on 2025-03-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('__data_processor__', '0024_metopiostatewideremovaldatatransformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolremovaldata',
            name='geoid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='__data_processor__.countygeoid'),
        ),
        migrations.AddField(
            model_name='schoolremovaldata',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolremovaldata',
            name='stratification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='__data_processor__.stratification'),
        ),
    ]
