# Generated by Django 3.2.25 on 2025-03-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('__data_processor__', '0025_auto_20250324_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyLayerRemovalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(default='County', max_length=50)),
                ('geoid', models.CharField(max_length=50)),
                ('topic', models.CharField(default='FVDEWVAR', max_length=50)),
                ('stratification', models.TextField(blank=True)),
                ('period', models.CharField(max_length=20)),
                ('value', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'County Layer Removal Data',
                'verbose_name_plural': 'County Layer Removal Data',
                'ordering': ['period', 'stratification'],
            },
        ),
        migrations.CreateModel(
            name='MetopioCityRemovalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(default='City', max_length=50)),
                ('geoid', models.CharField(max_length=50)),
                ('topic', models.CharField(default='FVDEWVAR', max_length=50)),
                ('stratification', models.TextField(blank=True)),
                ('period', models.CharField(max_length=20)),
                ('value', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'City Layer Removal Data',
                'verbose_name_plural': 'City Layer Removal Data',
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='MetopioTriCountyRemovalDataTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(default='Region', max_length=50)),
                ('geoid', models.CharField(default='fox-valley', max_length=50)),
                ('topic', models.CharField(default='FVDEWVAR', max_length=50)),
                ('stratification', models.TextField(blank=True)),
                ('period', models.CharField(max_length=20)),
                ('value', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Metopio Tri-County Removal Data Transformation',
                'verbose_name_plural': 'Metopio Tri-County Removal Data Transformations',
                'ordering': ['period', 'stratification'],
            },
        ),
        migrations.CreateModel(
            name='ZipCodeLayerRemovalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(default='County', max_length=50)),
                ('geoid', models.CharField(max_length=50)),
                ('topic', models.CharField(default='FVDEWVAR', max_length=50)),
                ('stratification', models.TextField(blank=True)),
                ('period', models.CharField(max_length=20)),
                ('value', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'County Layer Removal Data',
                'verbose_name_plural': 'County Layer Removal Data',
                'ordering': ['period', 'geoid', 'stratification'],
            },
        ),
    ]
