# Generated by Django 3.2.25 on 2025-03-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('__data_processor__', '0026_countylayerremovaldata_metopiocityremovaldata_metopiotricountyremovaldatatransformation_zipcodelayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedRemovalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(default='Combined', max_length=50)),
                ('geoid', models.CharField(max_length=50)),
                ('topic', models.CharField(default='FVDEWVAR', max_length=50)),
                ('stratification', models.TextField(blank=True)),
                ('period', models.CharField(max_length=20)),
                ('value', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Combined Removal Data',
                'verbose_name_plural': 'Combined Removal Data',
                'ordering': ['period'],
            },
        ),
    ]
