# Generated by Django 4.2.16 on 2025-12-01 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0027_combinedremovaldata"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForwardExamData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_year",
                    models.CharField(max_length=7, verbose_name="School Year"),
                ),
                (
                    "agency_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Agency Type"
                    ),
                ),
                (
                    "cesa",
                    models.CharField(blank=True, max_length=10, verbose_name="CESA"),
                ),
                (
                    "county",
                    models.CharField(blank=True, max_length=50, verbose_name="County"),
                ),
                (
                    "district_code",
                    models.CharField(max_length=10, verbose_name="District Code"),
                ),
                (
                    "school_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="School Code"
                    ),
                ),
                (
                    "grade_group",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Grade Group"
                    ),
                ),
                (
                    "charter_ind",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Charter Indicator"
                    ),
                ),
                (
                    "district_name",
                    models.CharField(max_length=100, verbose_name="District Name"),
                ),
                (
                    "school_name",
                    models.CharField(max_length=100, verbose_name="School Name"),
                ),
                (
                    "test_subject",
                    models.CharField(max_length=50, verbose_name="Test Subject"),
                ),
                (
                    "grade_level",
                    models.CharField(max_length=50, verbose_name="Grade Level"),
                ),
                (
                    "test_result",
                    models.CharField(max_length=50, verbose_name="Test Result"),
                ),
                (
                    "test_result_code",
                    models.CharField(max_length=50, verbose_name="Test Result Code"),
                ),
                (
                    "test_group",
                    models.CharField(max_length=100, verbose_name="Test Group"),
                ),
                ("group_by", models.CharField(max_length=50, verbose_name="Group By")),
                (
                    "group_by_value",
                    models.CharField(max_length=200, verbose_name="Group By Value"),
                ),
                (
                    "student_count",
                    models.CharField(max_length=20, verbose_name="Student Count"),
                ),
                (
                    "percent_of_group",
                    models.CharField(max_length=20, verbose_name="Percent of Group"),
                ),
                (
                    "group_count",
                    models.CharField(max_length=20, verbose_name="Group Count"),
                ),
                (
                    "forward_average_scale_score",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Forward Average Scale Score",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Place"
                    ),
                ),
                (
                    "geoid",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="__data_processor__.countygeoid",
                        verbose_name="GEOID",
                    ),
                ),
                (
                    "stratification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="__data_processor__.stratification",
                        verbose_name="Stratification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forward Exam Data",
                "verbose_name_plural": "Forward Exam Data",
                "ordering": [
                    "school_year",
                    "test_subject",
                    "grade_level",
                    "test_result",
                ],
                "indexes": [
                    models.Index(
                        fields=["school_year", "test_subject"],
                        name="D_data_proc_school__ed3801_idx",
                    ),
                    models.Index(
                        fields=["district_code", "school_code"],
                        name="D_data_proc_distric_6f0a98_idx",
                    ),
                    models.Index(
                        fields=["group_by", "group_by_value"],
                        name="D_data_proc_group_b_66deb2_idx",
                    ),
                ],
            },
        ),
    ]
