# Generated by Django 3.2.25 on 2025-12-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('__data_processor__', '0028_forwardexamdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardExamCityLayerTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(default='City or town', max_length=50)),
                ('geoid', models.CharField(max_length=50)),
                ('topic', models.CharField(default='FVDEHAAP', max_length=50)),
                ('stratification', models.TextField(blank=True)),
                ('period', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Forward Exam City Layer Transformation',
                'verbose_name_plural': 'Forward Exam City Layer Transformations',
                'ordering': ['period', 'geoid', 'stratification'],
            },
        ),
        migrations.CreateModel(
            name='ForwardExamCountyLayerTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(default='County', max_length=50)),
                ('geoid', models.CharField(max_length=50)),
                ('topic', models.CharField(default='FVDEHAAP', max_length=50)),
                ('stratification', models.TextField(blank=True)),
                ('period', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Forward Exam County Layer Transformation',
                'verbose_name_plural': 'Forward Exam County Layer Transformations',
                'ordering': ['period', 'geoid', 'stratification'],
            },
        ),
        migrations.CreateModel(
            name='ForwardExamStateWideTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(default='State', max_length=50)),
                ('geoid', models.CharField(default='WI', max_length=50)),
                ('topic', models.CharField(default='FVDEHAAP', max_length=50)),
                ('stratification', models.TextField(blank=True)),
                ('period', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Forward Exam Statewide Transformation',
                'verbose_name_plural': 'Forward Exam Statewide Transformations',
                'ordering': ['period', 'stratification'],
            },
        ),
        migrations.CreateModel(
            name='ForwardExamTriCountyTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(default='Region', max_length=50)),
                ('geoid', models.CharField(default='fox-valley', max_length=50)),
                ('topic', models.CharField(default='FVDEHAAP', max_length=50)),
                ('stratification', models.TextField(blank=True)),
                ('period', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Forward Exam Tri-County Transformation',
                'verbose_name_plural': 'Forward Exam Tri-County Transformations',
                'ordering': ['period', 'stratification'],
            },
        ),
        migrations.CreateModel(
            name='ForwardExamZipCodeLayerTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(default='Zip Code', max_length=50)),
                ('geoid', models.CharField(max_length=50)),
                ('topic', models.CharField(default='FVDEHAAP', max_length=50)),
                ('stratification', models.TextField(blank=True)),
                ('period', models.CharField(max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Forward Exam Zip Code Layer Transformation',
                'verbose_name_plural': 'Forward Exam Zip Code Layer Transformations',
                'ordering': ['period', 'geoid', 'stratification'],
            },
        ),
    ]
