# Generated by Django 3.2.25 on 2025-12-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('__data_processor__', '0029_forwardexamcitylayertransformation_forwardexamcountylayertransformation_forwardexamstatewidetransfor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwardexamcitylayertransformation',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='forwardexamcountylayertransformation',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='forwardexamstatewidetransformation',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='forwardexamtricountytransformation',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='forwardexamzipcodelayertransformation',
            name='value',
            field=models.IntegerField(),
        ),
    ]
