# Generated by Django 3.2.25 on 2025-12-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('__data_processor__', '0030_forward_exam_value_to_integer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardExamCombinedTransformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(max_length=50)),
                ('geoid', models.CharField(max_length=50)),
                ('topic', models.CharField(default='FVDEHAAP', max_length=50)),
                ('stratification', models.TextField(blank=True)),
                ('period', models.CharField(max_length=20)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Forward Exam Combined Transformation',
                'verbose_name_plural': 'Forward Exam Combined Transformations',
                'ordering': ['period', 'layer', 'geoid', 'stratification'],
            },
        ),
    ]
