# Generated by Django 4.2.16 on 2026-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("__data_processor__", "0031_forwardexamcombinedtransformation"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentCombinedTransformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("layer", models.CharField(max_length=50)),
                ("geoid", models.CharField(max_length=50)),
                ("topic", models.CharField(default="FVDEYLCV", max_length=50)),
                ("stratification", models.TextField(blank=True)),
                ("period", models.CharField(max_length=20)),
                ("value", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Enrollment Combined Transformation",
                "verbose_name_plural": "Enrollment Combined Transformations",
                "ordering": ["period", "layer", "geoid", "stratification"],
            },
        ),
    ]
